cache = true
max_cache_age = "1d"
max_retries = 3
retry_wait_time = 2
timeout = 30
accept = ["200..=204", "429"]
scheme = ["https", "http"]
exclude_loopback = true
exclude = [
  '^https://www\.cac\.gov\.cn/',
  '^https://openai\.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/?$',
  '^https://openai\.com/index/introducing-chatgpt-search/?$',
  '^https://platform\.openai\.com/docs/api-reference/responses-streaming/response/web_search_call$',
]
exclude_path = [
  '(^|/)tmp/',
  '(^|/)node_modules/',
  '(^|/)\.next/',
]
