import { describe, expect, it, vi } from "vitest";
import { CONTRACT_VERSION, type ConversationQueueSnapshot } from "@talent-signal/contracts";
import { acceptConversationPreview, acceptConversationSnapshot, ConversationFrames } from "./conversation-stream";
import { clearConversationLocal, conversationExpiry, pruneConversationLocal, readConversationDraft, readConversationMessages, writeConversationDraft, writeConversationMessage, type LocalMessage } from "./conversation-local";
import { clearAllPendingSessionDrafts } from "../components/session-workbench/session-draft-pending";
function store(): Storage { const values = new Map<string, string>(); return { get length() { return values.size; }, key: i => [...values.keys()][i] ?? null, clear: () => values.clear(), getItem: k => values.get(k) ?? null, setItem: (k,v) => { values.set(k,v); }, removeItem: k => { values.delete(k); } }; }
const sid = "72ce7ff4-a5a8-40d0-b1d7-d84a13adcd30", mid = "a072ed54-6d56-413d-af4b-3ebc01ba646a";
function message(id=mid): LocalMessage { return {id,objective:"A retained message",createdAt:new Date().toISOString(),delivery:"unknown",expiresAt:conversationExpiry()}; }
const snapshot: ConversationQueueSnapshot = { contract_version:CONTRACT_VERSION,session_id:sid,revision:7,paused:false,queued:[],preview:null,active:{queue_entry_id:mid,message_id:mid,run_id:sid,revision:4,sequence:1,status:"running",objective:"test",created_at:new Date().toISOString(),updated_at:new Date().toISOString(),stage:"answer",cancel_requested:false,failure_code:null} };
describe("durable conversation delivery",()=>{
 it("retains separate messages across tab writes, scopes and reloads",()=>{const s=store();writeConversationMessage("owner",sid,message(),s);writeConversationMessage("owner",sid,message(sid),s);writeConversationMessage("other",sid,message(),s);expect(readConversationMessages("owner",sid,s)).toHaveLength(2);clearConversationLocal("owner",sid,s);expect(readConversationMessages("other",sid,s)).toHaveLength(1);});
 it("never acknowledges failed local persistence",()=>{const s=store();s.setItem=()=>{throw new Error("quota");};expect(writeConversationMessage("owner",sid,message(),s)).toBe(false);expect(writeConversationDraft("owner",sid,{value:"keep me",writer:"tab",updatedAt:new Date().toISOString(),expiresAt:conversationExpiry()},s)).toBe(false);});
 it("prunes expired and other-account evidence, and global logout clears both new stores",()=>{const s=store();writeConversationMessage("old",sid,message(),s);writeConversationMessage("current",sid,{...message(),expiresAt:Date.now()-1},s);writeConversationDraft("current",sid,{value:"current",writer:"tab",updatedAt:new Date().toISOString(),expiresAt:conversationExpiry()},s);pruneConversationLocal("current",s);expect(s.length).toBe(1);expect(readConversationDraft("current",sid,s)?.value).toBe("current");clearAllPendingSessionDrafts(s);expect(s.length).toBe(0);});
 it("bounds retention by the earlier Session deadline",()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-09-20T00:00:00Z"));expect(conversationExpiry("2026-09-20T01:00:00Z")).toBe(Date.parse("2026-09-20T01:00:00Z"));vi.useRealTimers();});
});
describe("incremental observation",()=>{
 it("handles every split point, CRLF, heartbeats and multiple frames",()=>{const payload=': heartbeat\r\n\r\nevent: preview\r\ndata: {"text":"逐步出现"}\r\n\r\nevent: reconnect\r\ndata: {}\r\n\r\n';for(let i=0;i<=payload.length;i++){const parser=new ConversationFrames();expect([...parser.push(payload.slice(0,i)),...parser.push(payload.slice(i))]).toEqual([{event:"preview",data:{text:"逐步出现"}},{event:"reconnect",data:{}}]);}});
 it("rejects old snapshots and forming text from a different run",()=>{expect(acceptConversationSnapshot(snapshot,{...snapshot,revision:6},sid)).toBe(snapshot);expect(acceptConversationSnapshot(snapshot,{...snapshot,session_id:mid},sid)).toBe(snapshot);const preview={run_id:sid,message_id:mid,text:"current",stage:"answer",revision:5};expect(acceptConversationPreview(null,preview,snapshot)).toEqual(preview);expect(acceptConversationPreview(preview,{...preview,run_id:mid,text:"stale"},snapshot)).toBe(preview);expect(acceptConversationPreview(preview,{...preview,revision:4,text:"older"},snapshot)).toBe(preview);expect(acceptConversationPreview(null,preview,{...snapshot,active:null})).toBeNull();});
 it("bounds malformed frames before they can consume unbounded memory",()=>{expect(()=>new ConversationFrames().push("x".repeat(500001))).toThrow();});
});
